candidate_name: "Haniszaim bin Nordin"
cv_path: "cv/HANISZAIM_RESUME.pdf"

locations:
  - "Selangor"
  - "Kuala Lumpur"
  - "Putrajaya"
  - "Johor Bahru"
  - "Cyberjaya"

roles:
  - "AI Engineer"
  - "ML Engineer"
  - "Computer Vision Engineer"
  - "NLP Engineer"
  - "MLOps Engineer"
  - "Data Scientist"
  - "AI Engineer"
  - "Machine Learning Engineer"
  - "Computer Vision Engineer"
  -  "NLP Engineer"
  - "MLOps Engineer"
  -  "Data Scientist"
  -  "Data Engineer"
  -  "Data Analyst"
  -  "Deep Learning Engineer"
  -  "LLM Engineer"
  -  "Generative AI Engineer"
  -  "AI Research Engineer"
  -  "AI Scientist"
  -  "Big Data Engineer"
  -  "AI Software Developer"
  -  "Backend AI Developer"
  -  "AI Automation Developer"
  - "AI Agent Developer"
  -  "Object Detection Engineer"
  -  "RAG Engineer"
  -  "AI Data Quality Analyst"
  -  "Big Data Engineer"
  -  "AI Data Annotator"
  -  "Video Analytics Engineer"
  -  "Autonomous Vehicle Vision Engineer"
  -  "Conversation Designer"
  -  "AI Platform Engineer"
  -  "Junior AI Engineer"
  -  "Junior Machine Learning Engineer"
    

experience_keywords:
  - "fresh grad"
  - "junior"
  - "graduate"
  - "0-2 years"
  - "entry level"

sheet_name: "Job Applications 2026"